# Generated by Django 4.2.7 on 2023-11-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_blocked',
        ),
    ]
