# Generated by Django 4.2.6 on 2023-11-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Armchair', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Corner Sofa', max_length=100),
        ),
    ]
