# Generated by Django 4.2.7 on 2023-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0002_remove_category_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
