# Generated by Django 4.2.7 on 2023-11-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0003_category_is_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_block',
            new_name='is_blocked',
        ),
    ]
