# Generated by Django 4.2.7 on 2023-12-14 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmart', '0007_cartorder_cartorderproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Wishlist_model',
        ),
    ]
