# Generated by Django 4.2.7 on 2024-01-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0014_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
    ]
