# Generated by Django 4.2.7 on 2024-01-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0015_remove_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
