# Generated by Django 4.2.7 on 2024-01-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmart', '0016_banner_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='banner',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
